"""Deterministic answer-confidence semantics for the AI explanation layer.

Confidence used to be one model-authored percentage that the probe guard then
raised to a floor of 75% whenever the model happened to agree with the engine.
Agreement is not evidence, and a sector with no probe reading cannot become more
certain because the sentence explaining it reads well.

Three independent axes are computed here from documented deterministic inputs and
reported separately:

``engine_confidence``
    The deterministic engine's own confidence in the recommendation being
    explained (``Recommendation.confidence_level``).  The AI layer may never
    raise it.  ``unknown`` when no recommendation exists — never ``low``, which
    would claim a judgement the engine did not make.

``data_quality``
    Freshness/completeness of the measured inputs behind that decision, taken
    from the canonical probe-state block (which already applies the thresholds in
    ``engine/staleness.py``).

``explanation_status``
    Whether the natural-language explanation itself was generated by the model,
    degraded to a deterministic fallback, or unavailable.  An explanation the
    model could not produce is not a confident answer, so it caps the compat
    score — but it never edits the two agronomic axes above.

``numeric_score`` remains for API compatibility (``confidence_score``); it is a
pure function of the two agronomic axes, capped by explanation availability.  No
model output participates in it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

EngineConfidence = Literal["high", "medium", "low", "unknown"]
DataQuality = Literal["fresh", "stale", "missing", "unknown"]
ExplanationStatus = Literal["generated", "degraded", "unavailable"]

DEGRADED_SCORE_CAP = 0.30

_ENGINE_LEVELS: dict[str, EngineConfidence] = {
    "high": "high",
    "medium": "medium",
    "low": "low",
}

# Engine confidence sets the ceiling; data quality can only lower it.
_ENGINE_SCORE: dict[str, float] = {
    "high": 0.85,
    "medium": 0.60,
    "low": 0.35,
    "unknown": 0.40,
}
_QUALITY_FACTOR: dict[str, float] = {
    "fresh": 1.00,
    "stale": 0.80,
    "missing": 0.65,
    "unknown": 0.80,
}

_ENGINE_LABEL_PT: dict[str, str] = {
    "high": "Confiança alta do motor determinístico",
    "medium": "Confiança média do motor determinístico",
    "low": "Confiança baixa do motor determinístico",
    "unknown": "Sem recomendação determinística recente para sustentar a confiança",
}
_QUALITY_LABEL_PT: dict[str, str] = {
    "fresh": "leituras de sonda actuais",
    "stale": "leituras de sonda antigas — o estado do solo pode ter mudado",
    "missing": "sem leitura directa do solo neste momento",
    "unknown": "qualidade dos dados de sonda não determinada",
}
_EXPLANATION_LABEL_PT: dict[str, str] = {
    "generated": "",
    "degraded": "Explicação de contingência — o serviço de IA não estava disponível",
    "unavailable": "Explicação indisponível",
}


@dataclass(frozen=True)
class AnswerConfidence:
    """The three axes plus the compatibility score, all server-derived."""

    engine_confidence: EngineConfidence
    data_quality: DataQuality
    explanation_status: ExplanationStatus
    score: float
    basis: str

    def to_dict(self) -> dict:
        return {
            "engine_confidence": self.engine_confidence,
            "data_quality": self.data_quality,
            "explanation_status": self.explanation_status,
            "score": self.score,
            "basis": self.basis,
        }


def _block(context, name: str) -> dict:
    if not isinstance(context, dict):
        return {}
    block = context.get(name)
    return block if isinstance(block, dict) else {}


def resolve_engine_confidence(context) -> EngineConfidence:
    """Read the engine's own confidence level; never infer one."""
    for candidate in (
        _block(context, "engine_decision").get("confidence_level"),
        context.get("confidence_level") if isinstance(context, dict) else None,
        # Probe-signal statistics carry the engine decision under this key.
        _block(context, "latest_recommendation").get("confidence_level"),
        _block(context, "recommendation").get("confidence_level"),
    ):
        if candidate is None:
            continue
        value = getattr(candidate, "value", candidate)
        level = _ENGINE_LEVELS.get(str(value).strip().lower())
        if level is not None:
            return level
    return "unknown"


def resolve_data_quality(context) -> DataQuality:
    """Grade the measured inputs from the canonical probe-state block."""
    probe_state = _block(context, "probe_state") or _block(context, "probe_summary")
    if not probe_state:
        return "unknown"
    if probe_state.get("live") is None:
        return "missing"
    quality = probe_state.get("data_quality")
    if not isinstance(quality, dict):
        return "unknown"
    total = quality.get("total_depths")
    stale = quality.get("stale_depths")
    fresh = quality.get("fresh_depths")
    if not isinstance(total, int) or total <= 0:
        return "unknown"
    if isinstance(stale, int) and stale > 0:
        return "stale"
    if isinstance(fresh, int) and fresh <= 0:
        return "missing"
    return "fresh"


def numeric_score(engine_confidence: str, data_quality: str) -> float:
    """Compatibility percentage — a pure function of the two agronomic axes."""
    base = _ENGINE_SCORE.get(engine_confidence, _ENGINE_SCORE["unknown"])
    factor = _QUALITY_FACTOR.get(data_quality, _QUALITY_FACTOR["unknown"])
    return round(max(0.0, min(1.0, base * factor)), 2)


def confidence_basis_pt(
    engine_confidence: str,
    data_quality: str,
    explanation_status: str,
) -> str:
    parts = [
        _ENGINE_LABEL_PT.get(engine_confidence, _ENGINE_LABEL_PT["unknown"]),
        _QUALITY_LABEL_PT.get(data_quality, _QUALITY_LABEL_PT["unknown"]),
    ]
    basis = " · ".join(part for part in parts if part)
    suffix = _EXPLANATION_LABEL_PT.get(explanation_status, "")
    return f"{basis} · {suffix}." if suffix else f"{basis}."


def derive_answer_confidence(
    context,
    *,
    explanation_status: ExplanationStatus = "generated",
) -> AnswerConfidence:
    engine_confidence = resolve_engine_confidence(context)
    data_quality = resolve_data_quality(context)
    score = numeric_score(engine_confidence, data_quality)
    if explanation_status != "generated":
        score = min(score, DEGRADED_SCORE_CAP)
    return AnswerConfidence(
        engine_confidence=engine_confidence,
        data_quality=data_quality,
        explanation_status=explanation_status,
        score=score,
        basis=confidence_basis_pt(engine_confidence, data_quality, explanation_status),
    )
