"""ai grounding chat actions and provenance

Revision ID: 019a556f37dd
Revises: 1c13f632d1a6
Create Date: 2026-09-10 11:30:27.963886

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019a556f37dd"
down_revision: str | None = "1c13f632d1a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_action",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("conversation_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("chat_message_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("farm_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("sector_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("recommendation_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'succeeded', 'failed', 'cancelled', 'invalidated')",
            name="ck_chat_action_status",
        ),
        sa.ForeignKeyConstraint(["chat_message_id"], ["chat_message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["conversation_id"], ["chat_conversation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["farm_id"], ["farm.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendation.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sector_id"], ["sector.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_chat_action_idempotency"),
    )
    op.create_index(
        "ix_chat_action_conversation",
        "chat_action",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_chat_action_message", "chat_action", ["chat_message_id"], unique=False)
    op.add_column("ai_response_feedback", sa.Column("reason", sa.String(length=40), nullable=True))
    op.add_column(
        "ai_response_feedback", sa.Column("context_version", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "ai_response_feedback", sa.Column("contract_version", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "chat_message",
        sa.Column("status", sa.String(length=20), server_default="complete", nullable=False),
    )
    op.add_column(
        "chat_message",
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "chat_message", sa.Column("context_version", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "chat_message", sa.Column("recommendation_id", sa.UUID(as_uuid=False), nullable=True)
    )
    op.add_column("chat_message", sa.Column("surface", sa.String(length=40), nullable=True))
    op.add_column(
        "chat_message", sa.Column("client_message_id", sa.String(length=80), nullable=True)
    )
    op.create_index(
        "uq_chat_message_client_id",
        "chat_message",
        ["conversation_id", "client_message_id"],
        unique=True,
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.create_foreign_key(
        "chat_message_recommendation_id_fkey",
        "chat_message",
        "recommendation",
        ["recommendation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # Autogenerate never emits CHECK constraints; the model declares this one and
    # an interrupted turn must not be storable as anything else.
    op.create_check_constraint(
        "ck_chat_message_status",
        "chat_message",
        "status IN ('complete', 'interrupted', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_chat_message_status", "chat_message", type_="check")
    op.drop_constraint("chat_message_recommendation_id_fkey", "chat_message", type_="foreignkey")
    op.drop_index(
        "uq_chat_message_client_id",
        table_name="chat_message",
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.drop_column("chat_message", "client_message_id")
    op.drop_column("chat_message", "surface")
    op.drop_column("chat_message", "recommendation_id")
    op.drop_column("chat_message", "context_version")
    op.drop_column("chat_message", "evidence")
    op.drop_column("chat_message", "status")
    op.drop_column("ai_response_feedback", "contract_version")
    op.drop_column("ai_response_feedback", "context_version")
    op.drop_column("ai_response_feedback", "reason")
    op.drop_index("ix_chat_action_message", table_name="chat_action")
    op.drop_index("ix_chat_action_conversation", table_name="chat_action")
    op.drop_table("chat_action")
    # ### end Alembic commands ###
