"""irrigation fingerprint table

Revision ID: 09ceb934819b
Revises: 6e5069f0c5fd
Create Date: 2026-07-06 11:23:24.037949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ceb934819b'
down_revision: Union[str, None] = '6e5069f0c5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_fingerprint',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('typical_event_net_mm', sa.Float(), nullable=False),
    sa.Column('typical_event_duration_min', sa.Float(), nullable=True),
    sa.Column('n_events', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', name='uq_irrigation_fingerprint_sector')
    )
    op.create_index(op.f('ix_irrigation_fingerprint_sector_id'), 'irrigation_fingerprint', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_fingerprint_sector_id'), table_name='irrigation_fingerprint')
    op.drop_table('irrigation_fingerprint')
    # ### end Alembic commands ###
