"""add flowmeter_reference table

Revision ID: 17e92505c5fb
Revises: 78fc0a618be2
Create Date: 2026-06-11 15:37:25.250206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e92505c5fb'
down_revision: Union[str, None] = '78fc0a618be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flowmeter_reference',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flowmeter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reference_rate_m3_ha', sa.Float(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), server_default='5.0', nullable=False),
    sa.Column('upper_limit_m3_ha', sa.Float(), nullable=False),
    sa.Column('lower_limit_m3_ha', sa.Float(), nullable=False),
    sa.Column('num_events_analyzed', sa.Integer(), nullable=False),
    sa.Column('std_dev', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_alert_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flowmeter_id'], ['flowmeter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flowmeter_id', name='uq_flowmeter_reference_flowmeter')
    )
    op.create_index(op.f('ix_flowmeter_reference_flowmeter_id'), 'flowmeter_reference', ['flowmeter_id'], unique=False)
    op.drop_index(op.f('flowmeter_reading_timestamp_idx'), table_name='flowmeter_reading')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('flowmeter_reading_timestamp_idx'), 'flowmeter_reading', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_flowmeter_reference_flowmeter_id'), table_name='flowmeter_reference')
    op.drop_table('flowmeter_reference')
    # ### end Alembic commands ###
