"""calibration sweep run

Revision ID: 1c13f632d1a6
Revises: 74126109d8e6
Create Date: 2026-07-28 19:42:26.381243

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c13f632d1a6'
down_revision: str | None = '74126109d8e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_sweep_run',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('farm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('sectors_total', sa.Integer(), nullable=True),
    sa.Column('sectors_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('applied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('no_candidate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('candidates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_sweep_run_farm_id'), 'calibration_sweep_run', ['farm_id'], unique=False)
    op.create_index('ix_calibration_sweep_run_farm_queued', 'calibration_sweep_run', ['farm_id', 'queued_at'], unique=False)
    op.create_index('uq_calibration_sweep_run_active', 'calibration_sweep_run', ['farm_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_calibration_sweep_run_active', table_name='calibration_sweep_run', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_calibration_sweep_run_farm_queued', table_name='calibration_sweep_run')
    op.drop_index(op.f('ix_calibration_sweep_run_farm_id'), table_name='calibration_sweep_run')
    op.drop_table('calibration_sweep_run')
    # ### end Alembic commands ###
