"""add ai feedback uniqueness index

Revision ID: 37eabad4a828
Revises: db60d960f6ea
Create Date: 2026-07-23 14:31:39.467645

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37eabad4a828'
down_revision: str | None = 'db60d960f6ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_ai_response_feedback_user_message', 'ai_response_feedback', ['user_id', 'chat_message_id'], unique=True, postgresql_where=sa.text('chat_message_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ai_response_feedback_user_message', table_name='ai_response_feedback', postgresql_where=sa.text('chat_message_id IS NOT NULL'))
    # ### end Alembic commands ###
