"""initial_schema

Revision ID: 624229864a91
Revises:
Create Date: 2026-04-07 10:53:36.728420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '624229864a91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_profile_template',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('name_pt', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('mad', sa.Float(), nullable=False, comment='Management allowable depletion 0-1'),
    sa.Column('root_depth_mature_m', sa.Float(), nullable=False),
    sa.Column('root_depth_young_m', sa.Float(), nullable=False),
    sa.Column('maturity_age_years', sa.Integer(), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_profile_template_crop_type'), 'crop_profile_template', ['crop_type'], unique=False)
    op.create_table('soil_preset',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name_pt', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('texture', sa.String(length=50), nullable=False),
    sa.Column('field_capacity', sa.Float(), nullable=False, comment='m³/m³'),
    sa.Column('wilting_point', sa.Float(), nullable=False, comment='m³/m³'),
    sa.Column('taw_mm_per_m', sa.Float(), nullable=False, comment='(FC-PWP)*1000 mm/m, for display'),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('farm',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('farm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('soil_texture', sa.String(length=50), nullable=True),
    sa.Column('field_capacity', sa.Float(), nullable=True, comment='m³/m³'),
    sa.Column('wilting_point', sa.Float(), nullable=True, comment='m³/m³'),
    sa.Column('stone_content_pct', sa.Float(), nullable=True),
    sa.Column('soil_preset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['soil_preset_id'], ['soil_preset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_farm_id'), 'plot', ['farm_id'], unique=False)
    op.create_table('weather_forecast',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('farm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_probability_pct', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecast_farm_id'), 'weather_forecast', ['farm_id'], unique=False)
    op.create_table('weather_observation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('farm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_mean_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('solar_radiation_mjm2', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True, comment='Pre-computed or engine-computed'),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observation_farm_id'), 'weather_observation', ['farm_id'], unique=False)
    op.create_index(op.f('ix_weather_observation_timestamp'), 'weather_observation', ['timestamp'], unique=False)
    op.create_table('sector',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plot_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=True),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True, comment='For annuals like maize'),
    sa.Column('tree_spacing_m', sa.Float(), nullable=True),
    sa.Column('row_spacing_m', sa.Float(), nullable=True),
    sa.Column('trees_per_ha', sa.Integer(), nullable=True),
    sa.Column('current_phenological_stage', sa.String(length=50), nullable=True),
    sa.Column('irrigation_strategy', sa.String(length=50), nullable=False),
    sa.Column('deficit_factor', sa.Float(), nullable=False),
    sa.Column('rainfall_effectiveness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_plot_id'), 'sector', ['plot_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('farm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title_pt', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('description_pt', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_farm_id'), 'alert', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alert_sector_id'), 'alert', ['sector_id'], unique=False)
    op.create_table('irrigation_system',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('emitter_flow_lph', sa.Float(), nullable=True, comment='L/h per emitter'),
    sa.Column('emitter_spacing_m', sa.Float(), nullable=True),
    sa.Column('lines_per_row', sa.Integer(), nullable=False),
    sa.Column('application_rate_mm_h', sa.Float(), nullable=True, comment='Computed or overridden by user'),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('max_runtime_hours', sa.Float(), nullable=True),
    sa.Column('min_irrigation_mm', sa.Float(), nullable=True),
    sa.Column('max_irrigation_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_system_sector_id'), 'irrigation_system', ['sector_id'], unique=True)
    op.create_table('probe',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probe_sector_id'), 'probe', ['sector_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('irrigation_depth_mm', sa.Float(), nullable=True),
    sa.Column('irrigation_runtime_min', sa.Float(), nullable=True),
    sa.Column('suggested_start_time', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_notes', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_sector_id'), 'recommendation', ['sector_id'], unique=False)
    op.create_table('sector_crop_profile',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('mad', sa.Float(), nullable=False),
    sa.Column('root_depth_mature_m', sa.Float(), nullable=False),
    sa.Column('root_depth_young_m', sa.Float(), nullable=False),
    sa.Column('maturity_age_years', sa.Integer(), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_customized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['source_template_id'], ['crop_profile_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_crop_profile_sector_id'), 'sector_crop_profile', ['sector_id'], unique=True)
    op.create_table('irrigation_event',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('applied_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_event_sector_id'), 'irrigation_event', ['sector_id'], unique=False)
    op.create_table('probe_depth',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('probe_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('depth_cm', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('calibration_offset', sa.Float(), nullable=False),
    sa.Column('calibration_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probe_depth_probe_id'), 'probe_depth', ['probe_id'], unique=False)
    op.create_table('recommendation_reason',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommendation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message_pt', sa.Text(), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('data_key', sa.String(length=100), nullable=True),
    sa.Column('data_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_reason_recommendation_id'), 'recommendation_reason', ['recommendation_id'], unique=False)
    op.create_table('probe_reading',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('probe_depth_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('calibrated_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['probe_depth_id'], ['probe_depth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_probe_reading_depth_time', 'probe_reading', ['probe_depth_id', 'timestamp'], unique=False)

    # Convert probe_reading to TimescaleDB hypertable (graceful — skips if TimescaleDB not available)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
                -- Drop UUID primary key so TimescaleDB can manage partitioning
                ALTER TABLE probe_reading DROP CONSTRAINT probe_reading_pkey;
                -- Add composite PK including timestamp
                ALTER TABLE probe_reading ADD PRIMARY KEY (id, timestamp);
                PERFORM create_hypertable('probe_reading', 'timestamp', if_not_exists => TRUE);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_probe_reading_depth_time', table_name='probe_reading')
    op.drop_table('probe_reading')
    op.drop_index(op.f('ix_recommendation_reason_recommendation_id'), table_name='recommendation_reason')
    op.drop_table('recommendation_reason')
    op.drop_index(op.f('ix_probe_depth_probe_id'), table_name='probe_depth')
    op.drop_table('probe_depth')
    op.drop_index(op.f('ix_irrigation_event_sector_id'), table_name='irrigation_event')
    op.drop_table('irrigation_event')
    op.drop_index(op.f('ix_sector_crop_profile_sector_id'), table_name='sector_crop_profile')
    op.drop_table('sector_crop_profile')
    op.drop_index(op.f('ix_recommendation_sector_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_probe_sector_id'), table_name='probe')
    op.drop_table('probe')
    op.drop_index(op.f('ix_irrigation_system_sector_id'), table_name='irrigation_system')
    op.drop_table('irrigation_system')
    op.drop_index(op.f('ix_alert_sector_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_farm_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_sector_plot_id'), table_name='sector')
    op.drop_table('sector')
    op.drop_index(op.f('ix_weather_observation_timestamp'), table_name='weather_observation')
    op.drop_index(op.f('ix_weather_observation_farm_id'), table_name='weather_observation')
    op.drop_table('weather_observation')
    op.drop_index(op.f('ix_weather_forecast_farm_id'), table_name='weather_forecast')
    op.drop_table('weather_forecast')
    op.drop_index(op.f('ix_plot_farm_id'), table_name='plot')
    op.drop_table('plot')
    op.drop_table('farm')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('soil_preset')
    op.drop_index(op.f('ix_crop_profile_template_crop_type'), table_name='crop_profile_template')
    op.drop_table('crop_profile_template')
