"""per plot weather

Revision ID: 6e5069f0c5fd
Revises: a35061e7720f
Create Date: 2026-07-03 12:15:06.785074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5069f0c5fd'
down_revision: Union[str, None] = 'a35061e7720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('myirrigation_project_id', sa.String(length=50), nullable=True))
    op.add_column('plot', sa.Column('weather_device_id', sa.String(length=50), nullable=True))
    op.add_column('weather_forecast', sa.Column('plot_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('ix_weather_forecast_farm_date'), table_name='weather_forecast')
    op.create_index('ix_weather_forecast_farm_plot_date', 'weather_forecast', ['farm_id', 'plot_id', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_weather_forecast_plot_id'), 'weather_forecast', ['plot_id'], unique=False)
    op.create_foreign_key(None, 'weather_forecast', 'plot', ['plot_id'], ['id'])
    op.add_column('weather_observation', sa.Column('plot_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('ix_weather_obs_farm_timestamp'), table_name='weather_observation')
    op.create_index('ix_weather_obs_farm_plot_timestamp', 'weather_observation', ['farm_id', 'plot_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weather_observation_plot_id'), 'weather_observation', ['plot_id'], unique=False)
    op.create_foreign_key(None, 'weather_observation', 'plot', ['plot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_observation', type_='foreignkey')
    op.drop_index(op.f('ix_weather_observation_plot_id'), table_name='weather_observation')
    op.drop_index('ix_weather_obs_farm_plot_timestamp', table_name='weather_observation')
    op.create_index(op.f('ix_weather_obs_farm_timestamp'), 'weather_observation', ['farm_id', 'timestamp'], unique=False)
    op.drop_column('weather_observation', 'plot_id')
    op.drop_constraint(None, 'weather_forecast', type_='foreignkey')
    op.drop_index(op.f('ix_weather_forecast_plot_id'), table_name='weather_forecast')
    op.drop_index('ix_weather_forecast_farm_plot_date', table_name='weather_forecast')
    op.create_index(op.f('ix_weather_forecast_farm_date'), 'weather_forecast', ['farm_id', 'forecast_date'], unique=False)
    op.drop_column('weather_forecast', 'plot_id')
    op.drop_column('plot', 'weather_device_id')
    op.drop_column('plot', 'myirrigation_project_id')
    # ### end Alembic commands ###
