"""farm calibration_auto_apply

Revision ID: 74126109d8e6
Revises: 37eabad4a828
Create Date: 2026-07-28 08:15:59.592002

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '74126109d8e6'
down_revision: str | None = '37eabad4a828'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('calibration_auto_apply', sa.Boolean(), server_default='false', nullable=False, comment='opt-in: weekly calibration job may apply its own results unattended'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'calibration_auto_apply')
    # ### end Alembic commands ###
