"""add flowmeter tables

Revision ID: 78fc0a618be2
Revises: l2m3n4o5p6q7
Create Date: 2026-05-22 11:38:54.744596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78fc0a618be2'
down_revision: Union[str, None] = 'l2m3n4o5p6q7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flowmeter',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_device_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowmeter_sector_id'), 'flowmeter', ['sector_id'], unique=True)
    op.create_table('flowmeter_reading',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flowmeter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_m3_ha', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flowmeter_id'], ['flowmeter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flowmeter_id', 'timestamp', name='uq_flowmeter_reading_device_ts')
    )
    op.create_index(op.f('ix_flowmeter_reading_flowmeter_id'), 'flowmeter_reading', ['flowmeter_id'], unique=False)
    # Convert to TimescaleDB hypertable (same pattern as probe_reading migration)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
                -- Drop UUID primary key so TimescaleDB can manage partitioning
                ALTER TABLE flowmeter_reading DROP CONSTRAINT flowmeter_reading_pkey;
                -- Add composite PK including timestamp
                ALTER TABLE flowmeter_reading ADD PRIMARY KEY (id, timestamp);
                PERFORM create_hypertable(
                    'flowmeter_reading', 'timestamp',
                    if_not_exists => TRUE,
                    migrate_data => TRUE
                );
            END IF;
        END $$;
    """)
    op.create_table('irrigation_event_detected',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flowmeter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('total_m3_ha', sa.Float(), nullable=False),
    sa.Column('peak_m3_ha', sa.Float(), nullable=False),
    sa.Column('num_readings', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flowmeter_id'], ['flowmeter.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flowmeter_id', 'start_time', name='uq_irrigation_event_detected_device_start')
    )
    op.create_index(op.f('ix_irrigation_event_detected_date'), 'irrigation_event_detected', ['date'], unique=False)
    op.create_index(op.f('ix_irrigation_event_detected_flowmeter_id'), 'irrigation_event_detected', ['flowmeter_id'], unique=False)
    op.create_index(op.f('ix_irrigation_event_detected_sector_id'), 'irrigation_event_detected', ['sector_id'], unique=False)
    op.drop_index(op.f('ix_alert_is_active'), table_name='alert')
    op.alter_column('irrigation_event', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment="'manual_log', 'controller', 'recommendation_accepted'",
               existing_nullable=False)
    op.drop_index(op.f('ix_irrigation_event_sector_start'), table_name='irrigation_event')
    op.alter_column('probe', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Provider's probe identifier",
               existing_nullable=False)
    op.alter_column('probe_depth', 'sensor_type',
               existing_type=sa.VARCHAR(length=50),
               comment="'moisture', 'temperature', 'ec'",
               existing_nullable=False)
    op.alter_column('probe_depth', 'data_status',
               existing_type=sa.VARCHAR(length=20),
               comment="'ok' | 'partial' | 'stale' | 'no_data' | 'unknown'",
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('probe_reading', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment="'vwc_m3m3', 'raw_counts', 'celsius', 'dS_m'",
               existing_nullable=False)
    op.drop_index(op.f('probe_reading_timestamp_idx'), table_name='probe_reading')
    op.drop_index(op.f('ix_provider_ingestion_run_started_at'), table_name='provider_ingestion_run')
    op.alter_column('recommendation', 'suggested_start_time',
               existing_type=sa.VARCHAR(length=10),
               comment='HH:MM',
               existing_nullable=True)
    op.drop_index(op.f('ix_recommendation_generated_at'), table_name='recommendation')
    op.alter_column('sector', 'auto_calibration_dismissed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='If set, auto-calibration suggestions are suppressed until this datetime',
               existing_nullable=True)
    op.alter_column('sector', 'current_phenological_stage',
               existing_type=sa.VARCHAR(length=50),
               comment="References a stage key from the sector's SectorCropProfile.stages",
               existing_nullable=True)
    op.alter_column('sector_crop_profile', 'source_template_id',
               existing_type=sa.UUID(),
               comment='Tracks origin template for reference; null if manually created',
               existing_nullable=True)
    op.alter_column('sector_override', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='e.g. forced depth mm',
               existing_nullable=True)
    op.alter_column('sector_override', 'valid_until',
               existing_type=sa.DATE(),
               comment='None = until manually removed',
               existing_nullable=True)
    op.drop_index(op.f('ix_weather_forecast_farm_date'), table_name='weather_forecast')
    op.drop_index(op.f('ix_weather_obs_farm_timestamp'), table_name='weather_observation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weather_obs_farm_timestamp'), 'weather_observation', ['farm_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weather_forecast_farm_date'), 'weather_forecast', ['farm_id', 'forecast_date'], unique=False)
    op.alter_column('sector_override', 'valid_until',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='None = until manually removed',
               existing_nullable=True)
    op.alter_column('sector_override', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='e.g. forced depth mm',
               existing_nullable=True)
    op.alter_column('sector_crop_profile', 'source_template_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tracks origin template for reference; null if manually created',
               existing_nullable=True)
    op.alter_column('sector', 'current_phenological_stage',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="References a stage key from the sector's SectorCropProfile.stages",
               existing_nullable=True)
    op.alter_column('sector', 'auto_calibration_dismissed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='If set, auto-calibration suggestions are suppressed until this datetime',
               existing_nullable=True)
    op.create_index(op.f('ix_recommendation_generated_at'), 'recommendation', ['generated_at'], unique=False)
    op.alter_column('recommendation', 'suggested_start_time',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='HH:MM',
               existing_nullable=True)
    op.create_index(op.f('ix_provider_ingestion_run_started_at'), 'provider_ingestion_run', ['started_at'], unique=False)
    op.create_index(op.f('probe_reading_timestamp_idx'), 'probe_reading', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('probe_reading', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'vwc_m3m3', 'raw_counts', 'celsius', 'dS_m'",
               existing_nullable=False)
    op.alter_column('probe_depth', 'data_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'ok' | 'partial' | 'stale' | 'no_data' | 'unknown'",
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('probe_depth', 'sensor_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="'moisture', 'temperature', 'ec'",
               existing_nullable=False)
    op.alter_column('probe', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Provider's probe identifier",
               existing_nullable=False)
    op.create_index(op.f('ix_irrigation_event_sector_start'), 'irrigation_event', ['sector_id', 'start_time'], unique=False)
    op.alter_column('irrigation_event', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="'manual_log', 'controller', 'recommendation_accepted'",
               existing_nullable=False)
    op.create_index(op.f('ix_alert_is_active'), 'alert', ['is_active'], unique=False)
    op.drop_index(op.f('ix_irrigation_event_detected_sector_id'), table_name='irrigation_event_detected')
    op.drop_index(op.f('ix_irrigation_event_detected_flowmeter_id'), table_name='irrigation_event_detected')
    op.drop_index(op.f('ix_irrigation_event_detected_date'), table_name='irrigation_event_detected')
    op.drop_table('irrigation_event_detected')
    op.drop_index(op.f('ix_flowmeter_reading_flowmeter_id'), table_name='flowmeter_reading')
    op.drop_table('flowmeter_reading')
    op.drop_index(op.f('ix_flowmeter_sector_id'), table_name='flowmeter')
    op.drop_table('flowmeter')
    # ### end Alembic commands ###
