"""link chat answers to durable user turns

Revision ID: a0d5b179c368
Revises: 019a556f37dd
Create Date: 2026-09-10 15:44:35.470947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0d5b179c368"
down_revision: str | None = "019a556f37dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message", sa.Column("reply_to_id", sa.UUID(as_uuid=False), nullable=True))
    op.add_column(
        "chat_message",
        sa.Column("response_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_unique_constraint("chat_message_reply_to_id_key", "chat_message", ["reply_to_id"])
    op.create_foreign_key(
        "chat_message_reply_to_id_fkey",
        "chat_message",
        "chat_message",
        ["reply_to_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_message_reply_to_id_fkey", "chat_message", type_="foreignkey")
    op.drop_constraint("chat_message_reply_to_id_key", "chat_message", type_="unique")
    op.drop_column("chat_message", "response_metadata")
    op.drop_column("chat_message", "reply_to_id")
    # ### end Alembic commands ###
