"""add project_id to farm_credentials

Revision ID: a35061e7720f
Revises: c602947c7784
Create Date: 2026-07-01 15:29:09.867087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35061e7720f'
down_revision: Union[str, None] = 'c602947c7784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_credentials', sa.Column('project_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_credentials', 'project_id')
    # ### end Alembic commands ###
