"""add probe_calibration

Revision ID: c602947c7784
Revises: 17e92505c5fb
Create Date: 2026-06-24 10:06:02.430297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c602947c7784'
down_revision: Union[str, None] = '17e92505c5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_calibration',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sector_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('observed_fc', sa.Float(), nullable=False),
    sa.Column('observed_refill', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('num_cycles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consistency', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', name='uq_probe_calibration_sector')
    )
    op.create_index(op.f('ix_probe_calibration_sector_id'), 'probe_calibration', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_probe_calibration_sector_id'), table_name='probe_calibration')
    op.drop_table('probe_calibration')
    # ### end Alembic commands ###
