"""add ai memory and feedback

Revision ID: db60d960f6ea
Revises: n4o5p6q7r8s9
Create Date: 2026-07-23 09:49:11.270017

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db60d960f6ea"
down_revision: str | None = "n4o5p6q7r8s9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversation",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("farm_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("sector_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["farm_id"], ["farm.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sector_id"], ["sector.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_conversation_user_farm_activity",
        "chat_conversation",
        ["user_id", "farm_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "field_observation",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("sector_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("author_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("observation_type", sa.String(length=50), nullable=False),
        sa.Column("structured_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("verified_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sector_id"], ["sector.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verified_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_field_observation_sector_observed",
        "field_observation",
        ["sector_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("conversation_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("proposed_action", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_chat_message_role"),
        sa.ForeignKeyConstraint(["conversation_id"], ["chat_conversation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_message_conversation_created",
        "chat_message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_response_feedback",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("farm_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("chat_message_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("surface", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating IN (-1, 1)", name="ck_ai_response_feedback_rating"),
        sa.ForeignKeyConstraint(["chat_message_id"], ["chat_message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["farm_id"], ["farm.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_response_feedback_surface_created",
        "ai_response_feedback",
        ["surface", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_response_feedback_surface_created", table_name="ai_response_feedback")
    op.drop_table("ai_response_feedback")
    op.drop_index("ix_chat_message_conversation_created", table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index("ix_field_observation_sector_observed", table_name="field_observation")
    op.drop_table("field_observation")
    op.drop_index("ix_chat_conversation_user_farm_activity", table_name="chat_conversation")
    op.drop_table("chat_conversation")
    # ### end Alembic commands ###
